import React, { useState } from 'react';
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import { AppConfig } from "@/components/AppConfig";
import { mockData } from "@/components/mockData";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Loader2, Mail, FileText, Calendar as CalendarIcon, MapPin } from "lucide-react";
import { format } from "date-fns";

export default function Reports() {
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [isSending, setIsSending] = useState(false);

  // Fetch logs for the selected date
  const { data: dailyLogs, isLoading } = useQuery({
    queryKey: ['dailyLogs', selectedDate],
    queryFn: async () => {
      if (AppConfig.demoMode.enabled) return mockData.logs;
      return base44.entities.DailyLog.list({
          query: { date: selectedDate },
          sort: { created_date: -1 }
      });
    },
    initialData: []
  });

  const handleSendReport = async () => {
    setIsSending(true);
    try {
      const currentUser = await base44.auth.me().catch(() => ({ email: 'user@example.com' }));
      
      if (AppConfig.demoMode.enabled) {
        await new Promise(resolve => setTimeout(resolve, 1000));
        alert(`DEMO MODE: Report would be sent to ${currentUser.email}`);
        setIsSending(false);
        return;
      }

      // Construct the email body
      const logsHtml = dailyLogs.map(log => `
        <div style="border: 1px solid #e2e8f0; padding: 15px; margin-bottom: 20px; border-radius: 8px;">
          <h3 style="color: #1e293b; margin-top: 0;">${log.crew_name}</h3>
          <p><strong>Location:</strong> ${log.location}</p>
          <p><strong>Work:</strong> ${log.work_performed}</p>
          <p><strong>Hours:</strong> ${log.hours_worked}</p>
          <p><strong>Notes:</strong> ${log.notes || 'N/A'}</p>
          ${log.photos && log.photos.length > 0 ? `
            <p><strong>Photos:</strong> <a href="${log.photos[0]}">View ${log.photos.length} Photos</a></p>
          ` : ''}
        </div>
      `).join('');

      const totalHours = dailyLogs.reduce((acc, log) => acc + (log.hours_worked || 0), 0);
      const crewCount = new Set(dailyLogs.map(log => log.crew_name)).size;

      const emailBody = `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #2563eb;">Daily Operations Report</h1>
          <p style="color: #64748b; font-size: 1.1em;">Date: ${format(new Date(selectedDate), 'MMMM d, yyyy')}</p>
          
          <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 5px 0;"><strong>Total Crews:</strong> ${crewCount}</p>
            <p style="margin: 5px 0;"><strong>Total Hours:</strong> ${totalHours}</p>
            <p style="margin: 5px 0;"><strong>Jobs Completed:</strong> ${dailyLogs.length}</p>
          </div>

          <h2>Crew Logs</h2>
          ${dailyLogs.length > 0 ? logsHtml : '<p>No logs submitted for this date.</p>'}
          
          <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 30px 0;" />
          <p style="color: #94a3b8; font-size: 0.8em;">Generated by ${AppConfig.branding.appName}</p>
        </div>
      `;

      await base44.integrations.Core.SendEmail({
        to: currentUser.email,
        subject: `Daily Report - ${format(new Date(selectedDate), 'MMM d, yyyy')}`,
        body: emailBody
      });

      alert(`Report sent successfully to ${currentUser.email}!`);
    } catch (error) {
      console.error("Failed to send report:", error);
      alert("Failed to send report. Please try again.");
    } finally {
      setIsSending(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-900">Daily Reports</h1>
          <p className="text-slate-500 mt-1">Generate and view summaries for specific dates.</p>
        </div>
        <div className="flex items-center gap-4 bg-white p-2 rounded-lg border border-slate-200 shadow-sm">
            <CalendarIcon className="w-5 h-5 text-slate-500 ml-2" />
            <Input 
              type="date" 
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
              className="border-0 focus-visible:ring-0 w-auto"
            />
        </div>
      </div>

      {/* Summary Cards */}
      {!isLoading && dailyLogs.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Card className="bg-blue-50 border-blue-100">
            <CardContent className="p-6 flex flex-col items-center text-center">
              <span className="text-blue-600 font-medium mb-1">Total Logs</span>
              <span className="text-3xl font-bold text-blue-700">{dailyLogs.length}</span>
            </CardContent>
          </Card>
          <Card className="bg-indigo-50 border-indigo-100">
            <CardContent className="p-6 flex flex-col items-center text-center">
              <span className="text-indigo-600 font-medium mb-1">Total Hours</span>
              <span className="text-3xl font-bold text-indigo-700">
                {dailyLogs.reduce((acc, log) => acc + (log.hours_worked || 0), 0)}
              </span>
            </CardContent>
          </Card>
          <Card className="bg-emerald-50 border-emerald-100">
            <CardContent className="p-6 flex flex-col items-center text-center">
              <span className="text-emerald-600 font-medium mb-1">Active Crews</span>
              <span className="text-3xl font-bold text-emerald-700">
                {new Set(dailyLogs.map(log => log.crew_name)).size}
              </span>
            </CardContent>
          </Card>
        </div>
      )}

      <Card className="border-slate-200 shadow-sm">
        <CardHeader className="flex flex-row items-center justify-between border-b border-slate-100 pb-4">
          <CardTitle className="text-xl font-semibold text-slate-800">
            Logs for {format(new Date(selectedDate), 'MMMM d, yyyy')}
          </CardTitle>
          <Button 
            onClick={handleSendReport}
            disabled={isSending || dailyLogs.length === 0}
            className="text-white"
            style={{ backgroundColor: AppConfig.branding.primaryColor }}
          >
            {isSending ? (
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            ) : (
              <Mail className="w-4 h-4 mr-2" />
            )}
            Email Report
          </Button>
        </CardHeader>
        <CardContent className="p-0">
          {isLoading ? (
            <div className="flex justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow className="bg-slate-50">
                  <TableHead>Crew</TableHead>
                  <TableHead>Location</TableHead>
                  <TableHead>Work Description</TableHead>
                  <TableHead className="text-right">Hours</TableHead>
                  <TableHead>Status</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {dailyLogs.length > 0 ? (
                  dailyLogs.map((log) => (
                    <TableRow key={log.id}>
                      <TableCell className="font-medium">{log.crew_name}</TableCell>
                      <TableCell>
                        <div className="flex items-center text-sm text-slate-600">
                          <MapPin className="w-3 h-3 mr-1" />
                          {log.location}
                        </div>
                      </TableCell>
                      <TableCell className="max-w-md">
                        <div className="truncate" title={log.work_performed}>
                          {log.work_performed}
                        </div>
                        {log.notes && (
                            <div className="text-xs text-slate-400 mt-1 truncate" title={log.notes}>
                                Note: {log.notes}
                            </div>
                        )}
                      </TableCell>
                      <TableCell className="text-right font-mono">{log.hours_worked}</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                          Submitted
                        </Badge>
                      </TableCell>
                    </TableRow>
                  ))
                ) : (
                  <TableRow>
                    <TableCell colSpan={5} className="text-center py-12 text-slate-400">
                      <FileText className="w-12 h-12 mx-auto mb-3 opacity-20" />
                      <p>No logs found for this date.</p>
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}